// <auto-generated />
namespace Red_Lake_Hospital_Redesign_Team6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EcardsFeatureKunalSailor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EcardsFeatureKunalSailor));
        
        string IMigrationMetadata.Id
        {
            get { return "202104111519080_E-cards Feature - Kunal Sailor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
