// <auto-generated />
namespace Red_Lake_Hospital_Redesign_Team6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class donation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(donation));
        
        string IMigrationMetadata.Id
        {
            get { return "202103290014235_donation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
