// <auto-generated />
namespace Red_Lake_Hospital_Redesign_Team6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_models_from_team_members_to_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_models_from_team_members_to_db));
        
        string IMigrationMetadata.Id
        {
            get { return "202104102340583_Add_models_from_team_members_to_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
